// Writes src/environments/environment.ts and environment.development.ts from environment
// variables. Runs automatically before `npm run build` (see package.json "prebuild").
//
// Locally, environment.ts already exists (copied from the .template.ts files per SETUP.md)
// and isn't tracked by git, so this script leaves it alone. On a CI/host build (e.g. Netlify),
// those files don't exist, so this generates them from env vars set in the host's dashboard —
// keeping real keys out of the repo while still producing a working build.
const fs = require('fs');
const path = require('path');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'CLOUDINARY_CLOUD_NAME',
  'CLOUDINARY_UPLOAD_PRESET',
];

const envDir = path.join(__dirname, '..', 'src', 'environments');
const prodPath = path.join(envDir, 'environment.ts');
const devPath = path.join(envDir, 'environment.development.ts');

const missing = required.filter((key) => !process.env[key]);

if (missing.length > 0) {
  if (fs.existsSync(prodPath) && fs.existsSync(devPath)) {
    console.log('generate-env: env vars not set, using existing local environment files.');
    process.exit(0);
  }
  console.error(
    `generate-env: environment files are missing and these env vars aren't set: ${missing.join(', ')}\n` +
      'Either copy the .template.ts files in src/environments (see SETUP.md) or set these env vars.',
  );
  process.exit(1);
}

const render = (production) => `// Auto-generated by scripts/generate-env.js from environment variables. Do not edit directly.
export const environment = {
  production: ${production},
  firebase: {
    apiKey: '${process.env.FIREBASE_API_KEY}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
    projectId: '${process.env.FIREBASE_PROJECT_ID}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${process.env.FIREBASE_APP_ID}',
  },
  cloudinary: {
    cloudName: '${process.env.CLOUDINARY_CLOUD_NAME}',
    uploadPreset: '${process.env.CLOUDINARY_UPLOAD_PRESET}',
  },
  // Optional — comma-separated emails allowed to edit/delete any recipe. Unset means no admins.
  adminEmails: ${JSON.stringify(
    (process.env.ADMIN_EMAILS ?? '')
      .split(',')
      .map((e) => e.trim())
      .filter(Boolean),
  )},
};
`;

fs.writeFileSync(prodPath, render(true));
fs.writeFileSync(devPath, render(false));
console.log('generate-env: wrote environment.ts and environment.development.ts from env vars.');
